#Faryal Alizai G01364057
#CS 262, Lab Section 202
#Lab 4

CC = gcc
CFLAGS = -g -Wall -std=c99 -pedantic-errors
LIBS = -lm
all: lab4_falizai4_202.c
	$(CC) lab4_falizai4_202.c -o lab4_falizai4_202 $(CFLAGS) $(LIBS)
clean:
	rm lab4_falizai4_202
