#Faryal Alizai G01364057
#CS 262, Lab Section 202
#Lab 2

CC = gcc
CFLAGS = -g -Wall -std=c99 -pedantic-errors
LIBS = -lm
all: lab2_falizai4_202.c
	$(CC) lab2_falizai4_202.c -o lab2_falizai4_202 $(CFLAGS) $(LIBS)
clean:
	rm lab2_falizai4_202
