#Faryal Alizai G01364057
#CS 262, Lab Section 202
#Lab 5

CC = gcc
CFLAGS = -g -Wall -std=c99 -pedantic-errors
LIBS = -lm
all: lab5_falizai4_202.c
	$(CC) lab5_falizai4_202.c -o lab5_falizai4_202 $(CFLAGS) $(LIBS)
clean:
	rm lab5_falizai4_202
