#Faryal Alizai G01364057
#CS 262, Lab Section 202
#Lab 6

CC = gcc
CFLAGS = -g -Wall -std=c99 -pedantic-errors
LIBS = -lm
TARGET = lab6_falizai4_202

$(TARGET) : $(TARGET).c
	$(CC) $(TARGET).c -o $(TARGET) $(CFLAGS) $(LIBS)
clean:
	rm $(TARGET)
