#Faryal Alizai G01364057
#CS 262, Lab Section 202
#Lab 11

CC = gcc
CLAGS = -g -Wall -std=c99 -pedantic-errors
LIBS = -lm
TARGET = lab11_falizai4_202
$(TARGET) : $(TARGET).c
	$(CC) $(TARGET).c -o $(TARGET) $(CFLAGS) $(LIBS)
clean:
	rm $(TARGET)     
