#Faryal Alizai G01364057
#CS 262, Lab Section 202
#P1

CC = gcc
CFLAGS = -g -Wall -std=c99 -pedantic-errors
TARGET = p1_falizai4_202
$(TARGET) : $(TARGET).c
	$(CC) $(TARGET).c -o $(TARGET) $(CFLAGS)

clean:
	rm $(TARGET)
