#Faryal Alizai G01364057
#CS 262, Lab Section 202
#Lab 3

CC = gcc
CFlAGS = -g -Wall -std=c99 -pedantic-errors
TARGET = lab3_falizai4_202
LIBS = -lm
all: $(TARGET)

$(TARGET): $(TARGET).c
	$(CC) $(TARGET).c -o $(TARGET) $(CFLAGS) $(LIBS)
clean:
	rm $(TARGET)
